### ISSUE TITLE
Facing crash

### ISSUE THREAD

**Issue by parthanjaria** [wajahatkarim3/MediumClap-Android#21]
I am trying to use the library and facing this crash. Any reason why?

Process: com.sharesmile.share, PID: 4231
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/florent37/viewanimator/ViewAnimator;
        at com.wajahatkarim3.clapfab.ClapFAB.fabScaleUpAnimation(ClapFAB.kt:337)
        at com.wajahatkarim3.clapfab.ClapFAB.playActualFabAnim(ClapFAB.kt:308)
        at com.wajahatkarim3.clapfab.ClapFAB.access$playActualFabAnim(ClapFAB.kt:28)
        at com.wajahatkarim3.clapfab.ClapFAB$init$$inlined$let$lambda$1.onClick(ClapFAB.kt:155)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24774)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.florent37.viewanimator.ViewAnimator" on path: DexPathList[[zip file "/data/app/com.sharesmile.share-Mvi7Cz-U1RVPpWEjgqZdAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.sharesmile.share-Mvi7Cz-U1RVPpWEjgqZdAw==/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.wajahatkarim3.clapfab.ClapFAB.fabScaleUpAnimation(ClapFAB.kt:337) 
        at com.wajahatkarim3.clapfab.ClapFAB.playActualFabAnim(ClapFAB.kt:308) 
        at com.wajahatkarim3.clapfab.ClapFAB.access$playActualFabAnim(ClapFAB.kt:28) 
        at com.wajahatkarim3.clapfab.ClapFAB$init$$inlined$let$lambda$1.onClick(ClapFAB.kt:155) 
        at android.view.View.performClick(View.java:6294) 
        at android.view.View$PerformClick.run(View.java:24774) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6501) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by parthanjaria** [comment]
anyone can help me?

**Comment by wajahatkarim3** [comment]
Let me check this. It seems that a library ViewAnimator has some issues and MediumClap is using that library for animations purposes.

**Comment by Shubhamsdr3** [comment]
@wajahatkarim3  was this fixed ?

**Comment by Shubhamsdr3** [comment]
I fixed it by adding dependency :  implementation 'com.github.florent37:viewanimator:1.1.0'
